### PR TITLE
Add Korean translations

### PR DESCRIPTION
**Pull request by lens0021**
Thank you!

### CODE REVIEW

**Comment by lens0021** [comment]
Could you review this please? @patarapolw

**Comment by patarapolw** [comment]
It's now in the [main branch](https://github.com/patarapolw/squirdle/blob/main/translation/ko.json), and built beautifully.

korean version

However, I am not sure if the app should be multilingual or deploy each languages separately, to account for the `<title>` and `<meta property="og:*">` tags.

As for the building instruction, either set envvar `SQ_LANG=ko` or edit `vite.config.ts` before building. (As a matter of fact, `SQ_LANG=en` works as well with the [same daily data set](https://github.com/Fireblend/squirdle/blob/main/fake-daily.csv).)

New daily list can also be created using `SQ_LANG=ko SQ_STARTDATE=2022-03-01 node scripts/make-daily.js`.

**Comment by lens0021** [comment]
Thank you for explaining how to build. I am also not sure about the problem you mentioned. I think you can reference some multilingual wordles:

- [POKÉDLE](https://pokedle.vercel.app/) is originally for Japanese but offers different versions under the routes(`/en`, `/ja`, `/es`, `/ru`, `/ko`, `/zh-hans` and `/zh-hant`)
- [Wordle Game](https://wordlegame.org/) and [Wordle Unlimited](https://mywordle.org/) do the same as POKÉDLE.
- [Jordle](https://jordle.jovid.win/home) and [WordleWordle](https://wordlewordle.com/) are multilingual but do not provide open graph tags.
- [Wordler](https://wordler.net/) and [Wordle Multilanguage](https://wordle.wekele.com/) are multilingual too but seem to provide open graph tags only in English.
- You can find more multilingual wordles on [WORDLES OF THE WORLD](https://rwmpelstilzchen.gitlab.io/wordles/) or [Wordle Hub](https://wordles.miraheze.org/wiki/Category:Multilingual_apps)

Thank you. @patarapolw

**Comment by patarapolw** [comment]
Korean Squirdle is now live at https://squirdle.polv.cc/ko

But I didn't add a button to change the language yet.

**Comment by lens0021** [comment]
Cool! Thank you for your efforts!

**Pull request closed without merging**
